# Generated by Django 2.0.1 on 2018-01-26 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20180126_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='direction',
            field=models.CharField(blank=True, choices=[('b', 'Buy'), ('s', 'Sell'), ('h', 'HODL')], default='b', help_text='Direction of trade', max_length=1),
        ),
    ]
