# Generated by Django 2.0.1 on 2018-01-29 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_news_direction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('sourceid', models.AutoField(help_text='source id', primary_key=True, serialize=False)),
                ('name', models.TextField(help_text='name of source/channel', max_length=100)),
                ('link', models.URLField(default='https://enot.channel', max_length=100)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5)),
                ('moderation_status', models.CharField(blank=True, choices=[('a', 'Added and sended for moderate'), ('p', 'Approved for view without owner'), ('o', 'Approved for view with owner'), ('d', 'Deleted from view')], default='a', help_text='Moderation status of source', max_length=1)),
                ('promo_status', models.CharField(blank=True, choices=[('n', 'No promo'), ('y', 'Promoted')], default='n', help_text='Promotion status of source', max_length=1)),
            ],
        ),
        migrations.AlterField(
            model_name='news',
            name='promo_status',
            field=models.CharField(blank=True, choices=[('n', 'No promo'), ('y', 'Promoted')], default='n', help_text='Promotion status of news', max_length=1),
        ),
        migrations.AddField(
            model_name='news',
            name='sourceid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Source'),
        ),
    ]
