# Generated by Django 2.0.1 on 2018-01-31 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20180130_0013'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['time']},
        ),
        migrations.AlterField(
            model_name='source',
            name='name',
            field=models.CharField(help_text='name of source/channel', max_length=100),
        ),
    ]
