# Generated by Django 2.0.1 on 2018-02-03 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20180131_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='dislike',
            field=models.IntegerField(blank=True, default=0, help_text='likes for new'),
        ),
        migrations.AddField(
            model_name='news',
            name='like',
            field=models.IntegerField(blank=True, default=0, help_text='likes for new'),
        ),
    ]
