# Generated by Django 2.0.1 on 2018-02-12 00:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='uservotes',
            name='vote_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
