# Generated by Django 2.0.1 on 2018-02-12 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_uservotes_vote_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='telegram',
            field=models.URLField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='source',
            name='text',
            field=models.TextField(default='', help_text='description of source', max_length=1000),
        ),
    ]
