# Generated by Django 2.0.1 on 2018-02-12 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_auto_20180212_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='telegram',
            field=models.URLField(default='', max_length=100),
        ),
    ]
