# Generated by Django 2.0.1 on 2018-02-13 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_auto_20180212_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='proof_image',
            field=models.ImageField(blank=True, height_field=200, upload_to='static/images/news', width_field=200),
        ),
    ]
