# Generated by Django 2.0.1 on 2018-02-13 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0023_auto_20180213_1438'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(help_text='banner id', primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='banner_images/')),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField(help_text='description of banner', max_length=1000)),
                ('link', models.URLField(max_length=100)),
            ],
        ),
    ]
