# Generated by Django 2.0.1 on 2018-02-13 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0024_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='count_click',
            field=models.IntegerField(blank=True, default=0, help_text='count of views'),
        ),
        migrations.AddField(
            model_name='banner',
            name='count_view',
            field=models.IntegerField(blank=True, default=0, help_text='count of views'),
        ),
        migrations.AddField(
            model_name='banner',
            name='status',
            field=models.BooleanField(default=False, help_text='status of promo - enabled, disabled'),
        ),
    ]
