# Generated by Django 2.0.1 on 2018-02-13 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0025_auto_20180213_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='count_click',
            field=models.IntegerField(blank=True, default=0, help_text='count of views', null=True),
        ),
        migrations.AlterField(
            model_name='banner',
            name='count_view',
            field=models.IntegerField(blank=True, default=0, help_text='count of views', null=True),
        ),
    ]
