# Generated by Django 2.0.1 on 2018-02-17 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0026_auto_20180213_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='text',
            field=models.TextField(help_text='description of banner', max_length=100),
        ),
        migrations.AlterField(
            model_name='banner',
            name='title',
            field=models.CharField(max_length=20),
        ),
    ]
