# Generated by Django 2.0.1 on 2018-02-18 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0033_auto_20180217_2116'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.AutoField(help_text='coin id', primary_key=True, serialize=False)),
                ('symbol', models.CharField(help_text='coin ticker', max_length=10)),
                ('name', models.CharField(max_length=20)),
                ('price', models.DecimalField(decimal_places=8, help_text='current price of coin', max_digits=20)),
                ('change', models.DecimalField(decimal_places=8, help_text='change of price 24 hour in perecents', max_digits=20)),
                ('volume', models.DecimalField(decimal_places=8, help_text='total volume in USD', max_digits=20)),
                ('mktcap', models.DecimalField(decimal_places=8, help_text='market cap in USD', max_digits=20)),
                ('image', models.ImageField(blank=True, height_field=256, upload_to='coin_images/', width_field=256)),
            ],
            options={
                'ordering': ['-volume'],
            },
        ),
        migrations.AddField(
            model_name='news',
            name='coinid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Coin'),
        ),
    ]
