# Generated by Django 2.0.1 on 2018-02-18 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0034_auto_20180219_0215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='image',
            field=models.ImageField(blank=True, upload_to='coin_images/'),
        ),
    ]
