# Generated by Django 2.0.1 on 2018-02-21 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0036_banner_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='coinprice',
            field=models.DecimalField(decimal_places=8, default=0, help_text='price of coin when news create', max_digits=20),
        ),
    ]
