# Generated by Django 2.0.1 on 2018-02-22 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0037_news_coinprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
