# Generated by Django 2.0.1 on 2018-03-16 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0043_auto_20180227_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='duration',
            field=models.CharField(blank=True, choices=[('4h', '4 hours'), ('1d', '1 day'), ('1w', '1 week')], default='1d', help_text='signal forecast duration', max_length=2),
        ),
    ]
