# Generated by Django 2.0.1 on 2018-03-16 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0045_auto_20180316_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='duration',
            field=models.CharField(choices=[('4h', '4 hours'), ('1d', '1 day'), ('1w', '1 week')], default='1w', help_text='signal forecast duration', max_length=2),
        ),
    ]
