# Generated by Django 2.0.1 on 2018-03-22 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0047_auto_20180321_0309'),
    ]

    operations = [
        migrations.AddField(
            model_name='uservotes',
            name='vote_rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='rate of vote', max_digits=10),
        ),
    ]
