# Generated by Django 2.0.1 on 2018-03-22 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0048_uservotes_vote_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='sum_all',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='sum of all vote_rate', max_digits=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='sum_positive',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='sum of all positive vote_rate', max_digits=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='sum_today',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='sum of all vote_rate last day', max_digits=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='sum_today_positive',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='sum of all positive vote_rate last day', max_digits=10),
        ),
    ]
