# Generated by Django 2.0.1 on 2018-03-24 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0049_auto_20180322_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='sum_dislikes',
            field=models.IntegerField(blank=True, default=0, help_text='dislikes of user'),
        ),
        migrations.AddField(
            model_name='profile',
            name='sum_likes',
            field=models.IntegerField(blank=True, default=0, help_text='likes of user'),
        ),
    ]
