# Generated by Django 2.0.1 on 2018-03-25 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0050_auto_20180325_0004'),
    ]

    operations = [
        migrations.AddField(
            model_name='uservotes',
            name='vote_rate_status',
            field=models.BooleanField(default=False, help_text='status of recalculation. If True - not change by rate_users.'),
        ),
    ]
