# Generated by Django 2.0.1 on 2018-03-30 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0053_yeenotsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='direction',
            field=models.CharField(blank=True, choices=[('b', 'Buy'), ('s', 'Sell')], default='b', help_text='Direction of trade', max_length=1),
        ),
    ]
