# Generated by Django 2.0.1 on 2018-04-01 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0055_auto_20180401_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='coinid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Coin', verbose_name='COIN'),
        ),
    ]
