# Generated by Django 2.0.1 on 2018-04-01 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0057_auto_20180402_0246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='sourceid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='catalog.Source', verbose_name='SOURCE'),
        ),
    ]
