# Generated by Django 2.0.1 on 2018-04-03 12:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0058_auto_20180402_0249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='direction',
            field=models.CharField(blank=True, choices=[('b', 'Buy'), ('s', 'Sell')], default='b', max_length=1, verbose_name='DIRECTION OF TRADE'),
        ),
        migrations.AlterField(
            model_name='news',
            name='duration',
            field=models.CharField(choices=[('4h', '4 hours'), ('1d', '1 day'), ('1w', '1 week')], default='1w', max_length=2, verbose_name='DURATION TIME OF FORECAST'),
        ),
        migrations.AlterField(
            model_name='news',
            name='proof_image',
            field=models.ImageField(blank=True, upload_to='news_images/', verbose_name='SCREENSHOT OF THE NEWS'),
        ),
        migrations.AlterField(
            model_name='news',
            name='text',
            field=models.TextField(max_length=1000, validators=[django.core.validators.MinLengthValidator(20)], verbose_name='DESCRIPTION OF NEWS'),
        ),
    ]
