# Generated by Django 2.0.1 on 2018-04-03 14:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0060_auto_20180403_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='text',
            field=models.TextField(help_text='YOUR MESSAGE MUST HAVE MORE THAN 20 CHARACTERS', max_length=1000, validators=[django.core.validators.MinLengthValidator(20)], verbose_name='DESCRIPTION OF NEWS'),
        ),
    ]
