# Generated by Django 2.0.1 on 2018-04-04 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0061_auto_20180403_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='count_link_click',
            field=models.IntegerField(blank=True, default=0, help_text='count of clicks to news link', null=True),
        ),
        migrations.AlterField(
            model_name='banner',
            name='count_click',
            field=models.IntegerField(blank=True, default=0, help_text='count of clicks to link', null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='link',
            field=models.URLField(default='https://yeenot.today', max_length=100),
        ),
    ]
