# Generated by Django 2.0.1 on 2018-04-05 17:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0063_source_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_sources', to=settings.AUTH_USER_MODEL),
        ),
    ]
