# Generated by Django 2.0.1 on 2018-04-15 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0067_promo_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promo_task',
            name='param',
            field=models.CharField(choices=[('w', 'Week'), ('m', 'Month')], default='w', help_text='Parameters of promo task', max_length=1),
        ),
        migrations.AlterField(
            model_name='promo_task',
            name='status',
            field=models.CharField(choices=[('o', 'Ordered'), ('p', 'Paid'), ('l', 'Launched'), ('c', 'Completed')], default='o', help_text='Status of promo task', max_length=1),
        ),
        migrations.AlterField(
            model_name='promo_task',
            name='type',
            field=models.CharField(choices=[('n', 'News promo'), ('s', 'Source promo'), ('b', 'Banner promo')], default='n', help_text='Type of promo task', max_length=1),
        ),
    ]
