# Generated by Django 2.0.1 on 2018-04-17 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0070_auto_20180417_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promo_task',
            name='type',
            field=models.CharField(blank=True, choices=[('n', 'News promo'), ('s', 'Source promo'), ('b', 'Banner promo')], help_text='Type of promo task', max_length=1),
        ),
    ]
