# Generated by Django 2.0.1 on 2018-04-18 13:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0071_auto_20180417_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='link',
            field=models.URLField(default='https://yeenot.today', verbose_name='REFERENCE ON NEWS:'),
        ),
        migrations.AlterField(
            model_name='news',
            name='text',
            field=models.TextField(help_text='YOUR MESSAGE MUST HAVE MORE THAN 20 CHARACTERS', max_length=2000, validators=[django.core.validators.MinLengthValidator(20)], verbose_name='DESCRIPTION OF NEWS'),
        ),
    ]
