# Generated by Django 2.0.1 on 2018-04-29 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0072_auto_20180418_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='count_details_view',
            field=models.IntegerField(blank=True, default=0, help_text='count of views of news detail', null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='duration',
            field=models.CharField(choices=[('4h', '4 hours'), ('1d', '1 day'), ('1w', '1 week'), ('2w', '2 week'), ('3w', '3 week'), ('1m', '1 month')], default='1w', max_length=2, verbose_name='DURATION TIME OF FORECAST'),
        ),
    ]
