# Generated by Django 2.0.1 on 2018-05-01 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0073_auto_20180429_1805'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-time']},
        ),
    ]
